### ISSUE TITLE
Point cloud from depth?

### ISSUE THREAD

**Issue by antithing** [menandro/vfs#1]
Hi, and thank you very much for making this code available! I have been fighting with getting accurate depth from a T265 for a week or so.

Is it possible to create a point cloud from the depth maps created by your code?
Would I need to apply undistortion to do this?

Thanks again!

**Comment by menandro** [comment]
Hi, this version only solves disparity so undistortion and triangulation is needed to convert to depth after. I'll have an updated version, soon.

**Comment by antithing** [comment]
Great, thank you!

Is it possible to have a cmake version of this code? i am having trouble building it using the sln. Thank you again!

**Comment by menandro** [comment]
I added the disparity-3D conversion with the Kanala-Brandt model.

**Comment by antithing** [comment]
Thank you!
