### ISSUE TITLE
encoding scale of depth groundtruth

### ISSUE THREAD

**Issue by wpfhtl** [menandro/vfs#11]
Hi, 
Thanks for your code and dataset. 
I have a question, what is the encoding scale of the depth groundtruth file? In your dataset, the groudtruth is a 16 bit png file, what's value means, Millimetre or something else? 
Best regards

**Comment by menandro** [comment]
Unit is meters, but you'll need to read the 16-bit value as INT then divide by 256 to convert to FLOAT in meters. It's in the same format as KITTI.
