### ISSUE TITLE
Update of dual variable p

### ISSUE THREAD

**Issue by dprov** [menandro/vfs#15]
In the VFS paper (and in the paper it cites) : 
<img src="https://user-images.githubusercontent.com/46375825/165954318-9ee713dc-b552-4c67-b535-afcbbfab8186.png" width="400"/>
<img src="https://user-images.githubusercontent.com/46375825/165951139-3078f44f-e5ee-4431-91bb-271917615883.png" width="400"/>

In contrast, in e.g.  https://openaccess.thecvf.com/content_iccv_2013/papers/Ferstl_Image_Guided_Depth_2013_ICCV_paper.pdf and https://link.springer.com/chapter/10.1007/978-3-319-46475-6_36 , it's rather
<img src="https://user-images.githubusercontent.com/46375825/165954532-5a432825-2534-4805-8e58-9bbabf787b74.png" width="400"/>
<img src="https://user-images.githubusercontent.com/46375825/165953794-833740bc-f02c-4df4-8e75-2b0b211d734d.png" width="400"/>

However, in [VFS's TGV solver](https://github.com/menandro/vfs/blob/master/stereotgv/updateDualVariables.cu), the way p is updated seems to follow these other papers : 
```
// NOTE: details/checks skipped for clarify.

 // u_x = dxp(u_) - v_(:, : , 1);
u_x = u_[right] - u_pos - v_pos.x;
 ...
 // du_tensor_x = a.*u_x + c.*u_y;
float du_tensor_x = a[pos] * u_x + c[pos] * u_y;
...
// p(:, : , 1) = p(:, : , 1) + alpha1*sigma / eta_p.*du_tensor_x;
  ppos.x = p[pos].x + (alpha1 * sigma / eta_p) * du_tensor_x;
...
```
Whereas I would have expected something like
```
// du_x = dxp(u_);
du_x = u_[right] - u_pos;
 ...
// du_tensor_x = a.*u_x + c.*u_y;
float du_tensor_x = a[pos] * du_x + c[pos] * du_y;
...
// p(:, : , 1) = p(:, : , 1) + alpha1*sigma / eta_p.*(du_tensor_x - v_(:, : , 1));
  ppos.x = p[pos].x + (alpha1 * sigma / eta_p) * (du_tensor_x - v_pos.x);
...
```
Would you be able to comment on that? Am I missing something?
Thanks

**Comment by menandro** [comment]
I might have missed which one I implemented, but your observation looks correct. I remember changing between two cases has really small effect on the smoothness of the depth, or at least the difference is very difficult to see.

**Comment by dprov** [comment]
Thanks for your reply, sorry I did not see it earlier. Indeed, it makes next to no differences, it was mostly about understanding what's happening.
