### ISSUE TITLE
About calibration and trajectory filed

### ISSUE THREAD

**Issue by yukitsuji** [menandro/vfs#2]
Hi @menandro,

Thank you for sharing the great work!
I would like to know how to generate the calibration and trajectory field.
Could you share the code about it?

Thanks.
Yuki

**Comment by menandro** [comment]
Hi, I will update the repo soon which includes this. But meanwhile, I can send you a Matlab script for generating the fields. (Only for Kannala-Brandt model)

**Comment by yukitsuji** [comment]
Thank you for your reply!
Could you send a script to yukitsuji020832@gmail.com?
I am also looking forward to seeing the updated code.

Thanks,
