### ISSUE TITLE
Function time

### ISSUE THREAD

**Issue by antithing** [menandro/vfs#4]
Hi, thanks again for making this code available.
I have it running on windows, Cuda 10.0, and am testing the `test_t265_data` function with the provided data.

It runs, and looks good, but the function takes 15 seconds.

When I adjust the :

```
int nWarpIters = 20;	// Change to reduce processing time
int nSolverIters = 20;	// Change to reduce processing time
```

It takes 843 milliseconds.

Is this the expected time? Is it possible for this code to run in realtime?

thanks!

**Comment by menandro** [comment]
Yes. You’ll have to mix and match the nWarpIters, and nSolverIters. 848x800 is too big for realtime, but I have tested for 10fps and not so accurate. 

The settings I use for my app is this:

float stereoScaling = 2.0f;
float lambda = 5.0f;
float nLevel = 5;
	float fScale = 2.0f;
	int nWarpIters = 5;
	int nSolverIters = 20;
	stereotgv->limitRange = 0.5f;

Lower lambda is smoother, but less accurate and needs higher nSolverIters. Lower lambda can be used for low nSolverIters. Low lambda and high nSolverIters is noisy.

**Comment by antithing** [comment]
Thanks! that is faster.

My result (from the provided data) look like this:

![depth](https://user-images.githubusercontent.com/11506730/77748560-7accf580-7018-11ea-9d3e-53c68efe147e.jpg)

Quite different from the results on this page! Am I doing something wrong?

**Comment by menandro** [comment]
This is optical flow, so it looks correct.

**Comment by antithing** [comment]
Okay thanks! One last question... How can I get a greyscale depth map?

**Comment by menandro** [comment]
In the `test_t265_data` function, the 32-bit float depth map is copied to `cv::Mat depth`.
