### ISSUE TITLE
Distortion parameters for dataset

### ISSUE THREAD

**Issue by dwisth** [menandro/vfs#5]
Hi Menandro,

Thanks for the great resource. I want to use your fisheye stereo dataset to test one of my algorithms but can't find the distortion parameters of the camera you used.

Do you know where I can find them?

Thanks!

**Comment by menandro** [comment]
Hi, the dataset is generated using the equidistant model with FOV=120deg. I'm not sure how to convert that to other models (Kannala-Brandt) to have a similar distortion coefficients.
